<?php

namespace BoutiqueBundle\Repository;

use BoutiqueBundle\Entity\Produit;

/**
 * ProdruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdruitRepository extends \Doctrine\ORM\EntityRepository
{
    // Si j'ai des  requête qui  concernent exclusivement la table produit, et qui sont spécifique... Je vais les coder ici plutôt que de le faire dans le controller. Cela maintient un controller plus claire/générique


    // Fonction pour récupèrer toutes les categories via le queryBuilder()
    public function findAllCategories(){
        //Nous avons besoin du manager ici pour utiliser queryBuilder
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
         $query->select('p.categorie')->distinct(true)->from(Produit::class, 'p')->orderBy('p.categorie', 'ASC');

         return $query->getQuery()->getResult();
    }

    // Fonction pour récupèrer toutes les categories via le createQuery()
    public function findAllCategories2(){
        //Nous avons besoin du manager ici pour utiliser createQuery()
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT DISTINCT p.categorie From BoutiqueBundle\Entity\Produit p ORDER BY p.categorie");

        return $query->getResult();

    }
}
